# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160529_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodefile',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
