# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:38
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160529_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadsession',
            old_name='sessionFile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='receivedBytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='uuid',
            field=models.CharField(default=api.models.generate_uuid4, max_length=32),
        ),
    ]
