# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160529_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodefile',
            name='size',
            field=models.IntegerField(default=9999999),
        ),
    ]
