# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transcodefile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodefile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('png', 'PNG Image'), ('tmp', 'Temporary')], default='tmp', max_length=3),
        ),
        migrations.AlterField(
            model_name='transcodefile',
            name='size',
            field=models.IntegerField(),
        ),
    ]
