# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160601_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('task_uuid', models.CharField(max_length=32)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TranscodeFile')),
            ],
        ),
    ]
