# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:20
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_convertjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(choices=[('mvk', 'Matroska'), ('png', 'PNG Image'), ('tmp', 'Temporary')], max_length=5)),
            ],
            bases=(api.models.FileMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='transcodefile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('png', 'PNG Image'), ('tmp', 'Temporary')], default='tmp', max_length=5),
        ),
        migrations.AddField(
            model_name='convertedfile',
            name='transcode_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TranscodeFile'),
        ),
    ]
