# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160603_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disk_space',
            field=models.BigIntegerField(default=10000000000.0),
        ),
    ]
