# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_disk_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodefile',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('mp3', 'MPEG 3 Audio'), ('mp4', 'MPEG 4 Video'), ('avi', 'Audio Video Interleaved')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transcodefile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('mp3', 'MPEG 3 Audio'), ('mp4', 'MPEG 4 Video'), ('avi', 'Audio Video Interleaved')], default='tmp', max_length=5),
        ),
    ]
