# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160607_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodefile',
            name='name',
            field=models.CharField(default='plop', max_length=256),
            preserve_default=False,
        ),
    ]
