# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transcodefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 7, 20, 12, 44, 821634, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
