# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_convertedfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodefile',
            name='media_type',
            field=models.CharField(default='video', max_length=32),
            preserve_default=False,
        ),
    ]
