# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transcodefile_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertjob',
            name='dest_codec',
            field=models.CharField(default='h264', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertjob',
            name='dest_format',
            field=models.CharField(default='mkv', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('mp3', 'MPEG 3'), ('mp4', 'MPEG 4'), ('avi', 'Audio Video Interleaved'), ('wav', 'Wave'), ('ogg', 'Theora Vorbis')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transcodefile',
            name='fileType',
            field=models.CharField(choices=[('mvk', 'Matroska'), ('mp3', 'MPEG 3'), ('mp4', 'MPEG 4'), ('avi', 'Audio Video Interleaved'), ('wav', 'Wave'), ('ogg', 'Theora Vorbis')], default='tmp', max_length=5),
        ),
    ]
