# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:34
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160609_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedfile',
            name='file_uuid',
            field=models.CharField(default=api.models.generate_uuid4, max_length=32),
        ),
    ]
